version: '3'
volumes:
  postgres:
services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
