CREATE TABLE cards (
  id SERIAL PRIMARY KEY,
  title VARCHAR NOT NULL,
  deck_id INTEGER NOT NULL REFERENCES decks (id),
  done BOOLEAN NOT NULL,
  finished_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
